services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.3
    container_name: weaviate
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      OLLAMA_API_ENDPOINT: 'http://ollama:11434'
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      WEAVIATE_URL: "http://weaviate:8080"
      OLLAMA_URL: "http://ollama:11434"
      OLLAMA_MODEL: "mistral"
    depends_on:
      - weaviate
      - ollama
    volumes:
      - ./docs:/app/docs

volumes:
  ollama_data: